name: Backend Tests
on: 
  push:
    branches: [main]
    paths: 
       - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Dependencies
        working-directory: backend
        run: pip install -r requirements.txt
      - name: Run Tests
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
          QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
          CLUSTER_ENDPOINT: ${{ secrets.CLUSTER_ENDPOINT }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: pytest backend/tests/ -v
  deploy:
      needs: test
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      runs-on: ubuntu-latest
      permissions: 
            deployments: write
            contents: read
      steps:
        - uses: actions/checkout@v3
        - name: Create .env file
          run: |
            echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}" >> .env
            echo "QDRANT_API_KEY=${{ secrets.QDRANT_API_KEY }}" >> .env
            echo "CLUSTER_ENDPOINT=${{ secrets.CLUSTER_ENDPOINT }}" >> .env
            echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> .env
            echo "HF_TOKEN=${{ secrets.HF_TOKEN }}" >> .env
        - name: Sync secrets to Render
          uses: aasmal97/RenderSecretsSync@v1.1.0
          with:
            ENV_FILE_PATH: "./.env"
            RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
            RENDER_SERVICE_NAME: "Movie-Recommender-App-1"
        - name: Deploy to Render
          uses: bounceapp/render-action@0.6.0
          with:
            render-token: ${{ secrets.RENDER_API_KEY }}
            github-token: ${{ secrets.GITHUB_TOKEN }}
            service-id: ${{ secrets.RENDER_SERVICE_ID }}
            retries: 20
            wait: 30000
            sleep: 30000
